version: '3.4'

services:
  dynamicemotionbasedplaylistgenerator:
    build:
      context: .
      dockerfile: Dockerfile
    image: dynamicemotionbasedplaylistgenerator
    ports:
      - "5002:5002"
      - "5678:5678"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py
    volumes:
      - .:/app
