version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "5000:5000"   
    environment:
      - ENV=development
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
